name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build
        env:
          EDGE_STORE_ACCESS_KEY: ${{ secrets.EDGE_STORE_ACCESS_KEY }}
          EDGE_STORE_SECRET_KEY: ${{ secrets.EDGE_STORE_SECRET_KEY }}
          NEXT_PUBLIC_SERVER_URL: http://localhost:8080

      - name: Typecheck
        run: npm run tsc

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
